name: Sync Scripts, Manifests & Assets

on:
  push:
    branches:
      - main
      - update/manifests

jobs:
  sync-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Cache Sync Hashes Scripts
        uses: actions/cache@v4
        with:
          path: .sync/scripts/cache/cache-hash.json
          key: sync-scripts-hash-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            sync-scripts-hash-${{ runner.os }}-

      - name: Cache Sync Hashes Manifests
        uses: actions/cache@v4
        with:
          path: .sync/manifests/cache/cache-hash.json
          key: sync-manifests-hash-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            sync-manifests-hash-${{ runner.os }}-

      - name: Cache Sync Hashes Assets
        uses: actions/cache@v4
        with:
          path: .sync/assets/cache/cache-hash.json
          key: sync-assets-hash-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            sync-assets-hash-${{ runner.os }}-

      - name: Install Dependencies
        run: npm ci

      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          environment: ${{ github.ref_name == 'main' && '' || 'staging' }}

      - name: Run Build & Sync
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_URL: ${{ github.ref_name == 'main' && vars.API_URL || vars.STAGING_API_URL }}
          BUCKET_PUBLIC_NAME: ${{ github.ref_name == 'main' && vars.BUCKET_PUBLIC_NAME || vars.STAGING_BUCKET_PUBLIC_NAME }}
          R2_ACCOUNT_ID: ${{ secrets.R2_ACCOUNT_ID }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: auto
        run: |
          node .sync/scripts/index.js
          node .sync/manifests/index.js
          node .sync/assets/index.js
          node .sync/assets/aws/index.js
